<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\NetSpy.snk</AssemblyOriginatorKeyFile>
    <MakeEverythingPublicAssemblies>Microsoft.CodeAnalysis.Workspaces</MakeEverythingPublicAssemblies>
    <MakeEverythingPublicIVTString>$(AssemblyName)</MakeEverythingPublicIVTString>
    <NoWarn>$(NoWarn);CS0436</NoWarn>
  </PropertyGroup>

  <Import Project="$(MSBuildProjectDirectory)\..\..\..\Build\MakeEverythingPublic\MakeEverythingPublic.tasks" />

  <ItemGroup>
    <ProjectReference Include="..\NetSpy.Roslyn.Internal\NetSpy.Roslyn.Internal.csproj" />
    <ProjectReference Include="..\NetSpy.Roslyn\NetSpy.Roslyn.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="$(RoslynVersion)" />
    <PackageReference Include="Microsoft.VisualStudio.Text.UI.Wpf" Version="$(MSVSTextVersion)" />
  </ItemGroup>

</Project>
