<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <Copyright>Copyright 2011-2014 AlphaSierraPapa for the SharpDevelop Team</Copyright>
    <Version>$(NetSpyAssemblyVersion)</Version>
    <InformationalVersion>$(NetSpyAssemblyInformationalVersion)</InformationalVersion>

    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\NetSpy.snk</AssemblyOriginatorKeyFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\NetSpy.Decompiler.ILSpy.Core.Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NetSpy.Decompiler.ILSpy.Core.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\NetSpy.Decompiler.ILSpy.Core.Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NetSpy.Decompiler.ILSpy.Core.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\NetSpy\NetSpy.Contracts.Logic\NetSpy.Contracts.Logic.csproj" />
    <ProjectReference Include="..\..\..\NetSpy\NetSpy.Decompiler\NetSpy.Decompiler.csproj" />
    <ProjectReference Include="..\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler.csproj" />
    <ProjectReference Include="..\ICSharpCode.Decompiler\NRefactory.VB\ICSharpCode.NRefactory.VB\ICSharpCode.NRefactory.VB.csproj" />
    <ProjectReference Include="..\NRefactory\ICSharpCode.NRefactory.CSharp\ICSharpCode.NRefactory.CSharp.csproj" />
    <ProjectReference Include="..\NRefactory\ICSharpCode.NRefactory\ICSharpCode.NRefactory.csproj" />
  </ItemGroup>

</Project>
