<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <Import Project="..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <Copyright>$(NetSpyAssemblyCopyright)</Copyright>
    <Version>$(NetSpyAssemblyVersion)</Version>
    <InformationalVersion>$(NetSpyAssemblyInformationalVersion)</InformationalVersion>

    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\NetSpy.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetSpy.Contracts.Logic\NetSpy.Contracts.Logic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\NetSpy.Contracts.App.Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NetSpy.Contracts.App.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\NetSpy.Contracts.App.Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NetSpy.Contracts.App.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="$(OokiiDialogsWpfVersion)" />
    <PackageReference Include="System.ComponentModel.Composition" Version="$(DotNetPackageVersion)" />
    <PackageReference Include="Microsoft.VisualStudio.Language.Intellisense" Version="$(MSVSIntellisenseVersion)" />
    <PackageReference Include="Microsoft.VisualStudio.Text.UI.Wpf" Version="$(MSVSTextVersion)" />
    <PackageReference Include="System.Formats.Nrbf" Version="$(DotNetPackageVersion)" />
  </ItemGroup>

</Project>
