<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <Copyright>$(NetSpyAssemblyCopyright)</Copyright>
    <Version>$(NetSpyAssemblyVersion)</Version>
    <InformationalVersion>$(NetSpyAssemblyInformationalVersion)</InformationalVersion>

    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\NetSpy.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\NetSpy.Contracts.Logic.Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NetSpy.Contracts.Logic.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\NetSpy.Contracts.Logic.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>NetSpy.Contracts.Logic.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="$(DnlibVersion)" />
    <PackageReference Include="NuGet.Configuration" Version="$(NuGetVersion)" />
    <!-- TODO: HACK to resolve the version conflict of System.Collections.Immutable between NuGet.Configuration and Roslyn-->
    <PackageReference Include="System.Collections.Immutable" Version="$(DotNetPackageVersion)" />
  </ItemGroup>

</Project>
