<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <Import Project="..\..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <AssemblyName>Example1.Extension.x</AssemblyName>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\NetSpy\NetSpy.Contracts.App\NetSpy.Contracts.App.csproj" />
    <ProjectReference Include="..\..\..\NetSpy\NetSpy.Contracts.Logic\NetSpy.Contracts.Logic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Text.UI.Wpf" Version="$(MSVSTextVersion)" />
  </ItemGroup>

</Project>
