<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <Copyright>$(NetSpyAssemblyCopyright)</Copyright>
    <Version>$(NetSpyAssemblyVersion)</Version>
    <InformationalVersion>$(NetSpyAssemblyInformationalVersion)</InformationalVersion>

    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\NetSpy.snk</AssemblyOriginatorKeyFile>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>

    <DefineConstants>$(DefineConstants);APPHOSTINFO_STRINGS;APPHOSTINFO_DUPES;APPHOSTINFO_ERROR_STRINGS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\NetSpy.Debugger.DotNet.CorDebug\Impl\AppHostInfo.cs" Link="AppHostInfo.cs" />
    <Compile Include="..\NetSpy.Debugger.DotNet.CorDebug\Impl\AppHostInfoData.cs" Link="AppHostInfoData.cs" />
    <Compile Include="..\NetSpy.Debugger.DotNet.CorDebug\Impl\AppHostInfoData.g.cs" Link="AppHostInfoData.g.cs" />
    <Compile Include="..\NetSpy.Debugger.DotNet.CorDebug\Impl\ExeUtils.cs" Link="ExeUtils.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
  </ItemGroup>

  <ItemGroup Condition=" '$(IsDotNetFramework)' == 'true' ">
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
