<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <Import Project="..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <Copyright>$(NetSpyAssemblyCopyright)</Copyright>
    <Version>$(NetSpyAssemblyVersion)</Version>
    <InformationalVersion>$(NetSpyAssemblyInformationalVersion)</InformationalVersion>

    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\NetSpy.snk</AssemblyOriginatorKeyFile>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\NetSpy.Decompiler.Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NetSpy.Decompiler.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\NetSpy.Decompiler.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>NetSpy.Decompiler.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetSpy.Contracts.Logic\NetSpy.Contracts.Logic.csproj" />
  </ItemGroup>

</Project>
