<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\NetSpyCommon.props" />

  <PropertyGroup>
    <Copyright>$(NetSpyAssemblyCopyright)</Copyright>
    <Version>$(NetSpyAssemblyVersion)</Version>
    <InformationalVersion>$(NetSpyAssemblyInformationalVersion)</InformationalVersion>

    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\NetSpy.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Impl\ReflectionTests.cs" />
    <None Include="Impl\ReflectionTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="$(DnlibVersion)" />
  </ItemGroup>

</Project>
